Repository AbbeyIT/Stackie-2023-resolution, pull requests merged in 2023-01, with the labels that each got.

#7 Add Raviz to STACKIES
  STACKIES.md
Labels: small, waiting-for-review

#11 add ONLYBOND to stackies
  STACKIES.md
Labels: small, waiting-for-review

#10 Kodyvim added resolution to STACKIES.md file
  STACKIES.md
Labels: small, waiting-for-review

#12 Development
  STACKIES.md
Labels: small, waiting-for-review

#13 itscurious resolution
  STACKIES.md
Labels: small, waiting-for-review

#15 add Tian to Stackies
  STACKIES.md
Labels: small, medium, waiting-for-review

#17 add Flov9 to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#20 add Nakul to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#23 Add hottie to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#24 Update STACKIES.md
  STACKIES.md
Labels: small, waiting-for-review

#25 add TimmyKwesi to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#27 add Brian to Stackies.md
  STACKIES.md
Labels: small, waiting-for-review

#28 add Brayan1a1 to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#18 add That_Boii to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#22 Retr0.eth
  STACKIES.md
Labels: small, waiting-for-review

#26 add Haykay to Stackies
  STACKIES.md
Labels: small, waiting-for-review

#30 added Nikunj in Stackies
  STACKIES.md
Labels: small, LGTM

#31 Add Complexlity to Stackies
  STACKIES.md
Labels: small, waiting-for-review
